// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Lwaw3w1NRjTAn8Q51I5qPM2QnuOWb0E',
    appId: '1:488737656648:web:d8142481ac0b27fda92d7d',
    messagingSenderId: '488737656648',
    projectId: 'my-outdoor-daily-8ce1c',
    authDomain: 'my-outdoor-daily-8ce1c.firebaseapp.com',
    storageBucket: 'my-outdoor-daily-8ce1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct-rdinuD4Ek4140u4irzyx57qh6KTGA',
    appId: '1:488737656648:android:93d76b00ee314c8da92d7d',
    messagingSenderId: '488737656648',
    projectId: 'my-outdoor-daily-8ce1c',
    storageBucket: 'my-outdoor-daily-8ce1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4U_7JTgbFKjHYwzDwLsOA1_QJmtnB5yI',
    appId: '1:488737656648:ios:6583fa00b8355fe1a92d7d',
    messagingSenderId: '488737656648',
    projectId: 'my-outdoor-daily-8ce1c',
    storageBucket: 'my-outdoor-daily-8ce1c.appspot.com',
    iosClientId: '488737656648-pf3kadvjnifrnim8ng8btksamqf8n622.apps.googleusercontent.com',
    iosBundleId: 'com.example.myOutdoorDaily',
  );
}
